all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: <?php echo ProjectConfiguration::$platformConfig['database']['dsn'] . "\n"; ?>
      username: <?php echo ProjectConfiguration::$platformConfig['database']['db_user'] . "\n"; ?>
      password: <?php echo ProjectConfiguration::$platformConfig['database']['db_pass'] . "\n"; ?>
